### ISSUE TITLE
TODO Highlight configuration does not match exactly screenshot

### ISSUE THREAD

**Issue by vsakkas** [ykray/Lightbulb#4]
Hi, I am trying to replicate the setup I see on the screenshot, but I noticed that in your configuration there is one setting missing, which is:
```
    "todohighlight.defaultStyle": { "isWholeLine": true },
```
After adding this line, the highlighting for TODOs matches better your configuration.

**Comment by ykray** [comment]
Thanks for the catch! Amended the README for TODO Highlight setup

**Comment by ykray** [comment]
The screenshot needs to be updated overall — I made the promo banner quite a while ago, Lightbulb has been touched up heavily since then, so that's something that I need to update as well.
